defaults:
  - config: 04_eval_merit_basins_exp_1.yaml
  - _self_
# Global ------------------------------------------------------------------------
cwd: /projects/mhpi/tbindas/dmc-juniata-dev
data_dir: /projects/mhpi/data/dMC-Juniata-hydroDL2/dx-2000dis1_non_merge
name: 01_workshop_example
device: cpu
device_num: cpu
